CREATE DATABASE AppQLHV
GO
USE AppQLHV
GO

CREATE TABLE HocVien(
	MaHV CHAR(11) PRIMARY KEY ,
	HoTen NVARCHAR(30) DEFAULT NULL,
	NgaySinh DATETIME DEFAULT NULL,
	GioiTinh bit NOT NULL,
	DienThoai VARCHAR(10) DEFAULT NULL,
	DiaChi NVARCHAR(30) DEFAULT NULL,
	TinhTrang BIT NOT NULL
)


CREATE TABLE KhoaHoc(
	MaKH CHAR(11) PRIMARY KEY ,
	TenKH NVARCHAR(30) DEFAULT NULL,
	MoTa NVARCHAR(30) DEFAULT NULL,
	NgayBD DATETIME DEFAULT NULL,
	NgayKT DATETIME DEFAULT NULL,
	TinhTrang BIT NOT NULL
)

CREATE TABLE LopHoc(
	MaLop CHAR(11) PRIMARY KEY,
	MaKH CHAR(11) REFERENCES dbo.KhoaHoc(MaKH),
	MaHV CHAR(11) REFERENCES dbo.HocVien(MaHV),
	NgayDK DATETIME DEFAULT NULL,
	TinhTrang BIT NOT NULL
)

