CREATE DATABASE Lab06_QLHV
GO
USE Lab06_QLHV
GO


CREATE TABLE CaHoc
(Ca TINYINT PRIMARY KEY,
GioBatDau DATETIME ,
GioKetThuc DATETIME  
)
GO
CREATE TABLE GiaoVien
(MSGV CHAR(4) PRIMARY KEY,
HoGV NVARCHAR(20)NOT NULL,
TenGV NVARCHAR(10) NOT NULL,
DienThoai VARCHAR(6)
)
GO
CREATE TABLE Lop
(MaLop CHAR(4) PRIMARY KEY,
TenLop VARCHAR(15) NOT NULL,
NgayKG DATETIME,
HocPhi INT CHECK(HocPhi>0),
Ca TINYINT REFERENCES dbo.CaHoc(Ca),
SoTiet TINYINT,
SoHV TINYINT CHECK(SoHV<=30),
MSGV CHAR(4) REFERENCES dbo.GiaoVien(MSGV)
)
GO
CREATE TABLE HocVien
(
MSHV CHAR(10) PRIMARY KEY,
Ho NVARCHAR(20),
Ten NVARCHAR(10),
NgaySinh DATETIME,
Phai CHAR(3),
MaLop CHAR(4) REFERENCES dbo.Lop(MaLop)
)
GO
CREATE TABLE HocPhi
(SoBL CHAR(4) PRIMARY KEY,
MSHV CHAR(10) REFERENCES dbo.HocVien(MSHV),
NgayThu DATETIME,
SoTien INT CHECK(SoTien < (dbo.Lop.HocPhi)),
NoiDung VARCHAR(20),
NguoiThu NVARCHAR(10) NOT NULL
)
GO

